name: govulncheck
version: 1.0.4
base: core22
summary: Go vulnerability database checker
description: |
  Govulncheck reports known vulnerabilities that affect Go code.

  It uses static analysis of source code or a binary's symbol table
  to narrow down reports to only those that could affect the application.

  For more information about the API behind govulncheck, see
  https://go.dev/security/vulncheck.
adopt-info: govulncheck

grade: stable
confinement: classic

apps:
  govulncheck:
    command: bin/govulncheck
    plugs:
      - home
      - network

parts:
  govulncheck:
    plugin: go
    source-type: git
    source-tag: v1.0.4
    source: https://go.googlesource.com/vuln
    build-snaps:
      - go/latest/stable
